
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.catastrophemod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.catastrophemod.item.WoodenSpearItem;
import net.mcreator.catastrophemod.item.WoodenKatanaItem;
import net.mcreator.catastrophemod.item.WoodenBowItem;
import net.mcreator.catastrophemod.item.WitherSkullFragmentItem;
import net.mcreator.catastrophemod.item.WhispersCurseItem;
import net.mcreator.catastrophemod.item.VenomousRoundItem;
import net.mcreator.catastrophemod.item.VeinStrikerItem;
import net.mcreator.catastrophemod.item.TwigItem;
import net.mcreator.catastrophemod.item.ThunderStarItem;
import net.mcreator.catastrophemod.item.ThornSwordItem;
import net.mcreator.catastrophemod.item.ThornItem;
import net.mcreator.catastrophemod.item.ThornInfestedArmorLootBundleItem;
import net.mcreator.catastrophemod.item.ThornBowItem;
import net.mcreator.catastrophemod.item.TearOfTheSeaItem;
import net.mcreator.catastrophemod.item.SwordMasteryCrestItem;
import net.mcreator.catastrophemod.item.StormShieldItem;
import net.mcreator.catastrophemod.item.StormCatalystItem;
import net.mcreator.catastrophemod.item.StormBowItem;
import net.mcreator.catastrophemod.item.StormArrowItem;
import net.mcreator.catastrophemod.item.StoneSpearItem;
import net.mcreator.catastrophemod.item.StarlitLacewingStaffItem;
import net.mcreator.catastrophemod.item.StarItem;
import net.mcreator.catastrophemod.item.StaffofVitalityItem;
import net.mcreator.catastrophemod.item.StaffOfThornsItem;
import net.mcreator.catastrophemod.item.SporesplosionItem;
import net.mcreator.catastrophemod.item.SporeStaffItem;
import net.mcreator.catastrophemod.item.SpiritInABottleItem;
import net.mcreator.catastrophemod.item.SpinachSoupItem;
import net.mcreator.catastrophemod.item.SpinachLeavesItem;
import net.mcreator.catastrophemod.item.SpellofPoisonItem;
import net.mcreator.catastrophemod.item.SpellofLightningItem;
import net.mcreator.catastrophemod.item.SpellTomeItem;
import net.mcreator.catastrophemod.item.SpellOfPhantomsItem;
import net.mcreator.catastrophemod.item.SpellOfFlamesItem;
import net.mcreator.catastrophemod.item.SpeartheGungnirItem;
import net.mcreator.catastrophemod.item.SpearOfNatureItem;
import net.mcreator.catastrophemod.item.SpearMasteryCrestItem;
import net.mcreator.catastrophemod.item.ShroomiumItem;
import net.mcreator.catastrophemod.item.ShroomiumIngotItem;
import net.mcreator.catastrophemod.item.ShroomBowItem;
import net.mcreator.catastrophemod.item.ShadowflameWhisperItem;
import net.mcreator.catastrophemod.item.ShadowflameSkullItem;
import net.mcreator.catastrophemod.item.ShadowflameScepterItem;
import net.mcreator.catastrophemod.item.ShadowflameFragmentItem;
import net.mcreator.catastrophemod.item.ShadowflameBursterItem;
import net.mcreator.catastrophemod.item.SepulcherLootBundleItem;
import net.mcreator.catastrophemod.item.SeaSwordItem;
import net.mcreator.catastrophemod.item.SeaSpearItem;
import net.mcreator.catastrophemod.item.SeaShovelItem;
import net.mcreator.catastrophemod.item.SeaPickaxeItem;
import net.mcreator.catastrophemod.item.SeaPendantItem;
import net.mcreator.catastrophemod.item.SeaHoeItem;
import net.mcreator.catastrophemod.item.SeaCrystalGeodeItem;
import net.mcreator.catastrophemod.item.SeaConchItem;
import net.mcreator.catastrophemod.item.SeaBowItem;
import net.mcreator.catastrophemod.item.SeaAxeItem;
import net.mcreator.catastrophemod.item.ScreenshakeTestItemItem;
import net.mcreator.catastrophemod.item.SandstormSurgeItem;
import net.mcreator.catastrophemod.item.RustyCogwheelItem;
import net.mcreator.catastrophemod.item.RustgunItem;
import net.mcreator.catastrophemod.item.RunningBootsItem;
import net.mcreator.catastrophemod.item.RottenHeartItem;
import net.mcreator.catastrophemod.item.RosxiteIngotItem;
import net.mcreator.catastrophemod.item.RodOfTeleportationItem;
import net.mcreator.catastrophemod.item.RiptideItem;
import net.mcreator.catastrophemod.item.RipsawItem;
import net.mcreator.catastrophemod.item.RingOfResilienceItem;
import net.mcreator.catastrophemod.item.Reinforced_IronArmorItem;
import net.mcreator.catastrophemod.item.ReinforcedShieldItem;
import net.mcreator.catastrophemod.item.ReinforcedPlatesItem;
import net.mcreator.catastrophemod.item.ReinforcedAxeItem;
import net.mcreator.catastrophemod.item.RawShroomiumItem;
import net.mcreator.catastrophemod.item.RawRosxiteItem;
import net.mcreator.catastrophemod.item.RawNatureiteItem;
import net.mcreator.catastrophemod.item.QuiverItem;
import net.mcreator.catastrophemod.item.PurifiedCalicoMushroomStewItem;
import net.mcreator.catastrophemod.item.PoisonedVinesItem;
import net.mcreator.catastrophemod.item.PoisonedIronHeartItem;
import net.mcreator.catastrophemod.item.PocketShieldGeneratorItem;
import net.mcreator.catastrophemod.item.PacifyingSightItem;
import net.mcreator.catastrophemod.item.OrbitalBarrageItem;
import net.mcreator.catastrophemod.item.OceanicArtifactItem;
import net.mcreator.catastrophemod.item.NightfallsDemiseItem;
import net.mcreator.catastrophemod.item.NetheriteSpearItem;
import net.mcreator.catastrophemod.item.NetheriteShieldItem;
import net.mcreator.catastrophemod.item.NetherTreadsItem;
import net.mcreator.catastrophemod.item.NautilusItem;
import net.mcreator.catastrophemod.item.NaturiteSpearItem;
import net.mcreator.catastrophemod.item.NaturiteShieldItem;
import net.mcreator.catastrophemod.item.NaturiteBowItem;
import net.mcreator.catastrophemod.item.NaturesStrikeItem;
import net.mcreator.catastrophemod.item.NaturesBlessingItem;
import net.mcreator.catastrophemod.item.NatureiteSwordItem;
import net.mcreator.catastrophemod.item.NatureiteShovelItem;
import net.mcreator.catastrophemod.item.NatureitePickaxeItem;
import net.mcreator.catastrophemod.item.NatureiteIngotItem;
import net.mcreator.catastrophemod.item.NatureiteHoeItem;
import net.mcreator.catastrophemod.item.NatureiteAxeItem;
import net.mcreator.catastrophemod.item.NatureiteArmorItem;
import net.mcreator.catastrophemod.item.NatureiteAppleItem;
import net.mcreator.catastrophemod.item.NatureDefenderItem;
import net.mcreator.catastrophemod.item.NatureBlessedSpiritStaffItem;
import net.mcreator.catastrophemod.item.MusicDiscVinesOfVenomItem;
import net.mcreator.catastrophemod.item.MusicDiscStrikeYouDownItem;
import net.mcreator.catastrophemod.item.MusicDiscSparkOfAShadowItem;
import net.mcreator.catastrophemod.item.MusicDiscProliferatingMushroomsItem;
import net.mcreator.catastrophemod.item.MusicDiscOvergrownGroveItem;
import net.mcreator.catastrophemod.item.MusicDiscOutsideOfTheAtmosphereItem;
import net.mcreator.catastrophemod.item.MusicDiscNethersFuryItem;
import net.mcreator.catastrophemod.item.MusicDiscEnlightenedStarlightItem;
import net.mcreator.catastrophemod.item.MusicDiscBattleOfStoneItem;
import net.mcreator.catastrophemod.item.MossItem;
import net.mcreator.catastrophemod.item.MineralWraithLootBundleItem;
import net.mcreator.catastrophemod.item.MarksmansCrestItem;
import net.mcreator.catastrophemod.item.ManaStarItem;
import net.mcreator.catastrophemod.item.ManaRoseItem;
import net.mcreator.catastrophemod.item.ManaPotionItem;
import net.mcreator.catastrophemod.item.LivingMossItem;
import net.mcreator.catastrophemod.item.LightningBladeStaffItem;
import net.mcreator.catastrophemod.item.LifepiercerItem;
import net.mcreator.catastrophemod.item.Lifepiercer2Item;
import net.mcreator.catastrophemod.item.Lifepiercer1Item;
import net.mcreator.catastrophemod.item.Lifepiercer0Item;
import net.mcreator.catastrophemod.item.LesserManaPotionItem;
import net.mcreator.catastrophemod.item.LeatherGloveItem;
import net.mcreator.catastrophemod.item.KnifeOfProficiencyItem;
import net.mcreator.catastrophemod.item.IronSpearItem;
import net.mcreator.catastrophemod.item.IronRoundItem;
import net.mcreator.catastrophemod.item.InfernalFragmentItem;
import net.mcreator.catastrophemod.item.IceSwordItem;
import net.mcreator.catastrophemod.item.IceSpearItem;
import net.mcreator.catastrophemod.item.IceBowItem;
import net.mcreator.catastrophemod.item.HuntsmanKnifeItem;
import net.mcreator.catastrophemod.item.HunterItem;
import net.mcreator.catastrophemod.item.HellbaneItem;
import net.mcreator.catastrophemod.item.HeartOfThornsItem;
import net.mcreator.catastrophemod.item.HauntedMirrorItem;
import net.mcreator.catastrophemod.item.GraveDiggerItem;
import net.mcreator.catastrophemod.item.GoldenSpearItem;
import net.mcreator.catastrophemod.item.GoldenBraceletItem;
import net.mcreator.catastrophemod.item.GloveoftheDesertsItem;
import net.mcreator.catastrophemod.item.FrozenShieldItem;
import net.mcreator.catastrophemod.item.FreezingStaffItem;
import net.mcreator.catastrophemod.item.FlamestrikeItem;
import net.mcreator.catastrophemod.item.FirebrandItem;
import net.mcreator.catastrophemod.item.ElectrifiedSpearItem;
import net.mcreator.catastrophemod.item.ElectrifiedRoundItem;
import net.mcreator.catastrophemod.item.ElectrifiedCopperSwordItem;
import net.mcreator.catastrophemod.item.EarthboundWraithLootBundleItem;
import net.mcreator.catastrophemod.item.EarthboundStaffItem;
import net.mcreator.catastrophemod.item.EarthboundCoreItem;
import net.mcreator.catastrophemod.item.EarthShattererItem;
import net.mcreator.catastrophemod.item.EarthGauntletItem;
import net.mcreator.catastrophemod.item.EarthBreakerItem;
import net.mcreator.catastrophemod.item.DiamondSpearItem;
import net.mcreator.catastrophemod.item.DiamondDetonationItem;
import net.mcreator.catastrophemod.item.CursedClothItem;
import net.mcreator.catastrophemod.item.CursedArmorItem;
import net.mcreator.catastrophemod.item.CrystallineEdgeItem;
import net.mcreator.catastrophemod.item.CrystalSpearItem;
import net.mcreator.catastrophemod.item.CrystalRoundItem;
import net.mcreator.catastrophemod.item.CrystalBowItem;
import net.mcreator.catastrophemod.item.CrimstoneGemItem;
import net.mcreator.catastrophemod.item.CrimsonRayItem;
import net.mcreator.catastrophemod.item.CrimsonDaggerItem;
import net.mcreator.catastrophemod.item.CopperTokenItem;
import net.mcreator.catastrophemod.item.CopperShardItem;
import net.mcreator.catastrophemod.item.CatastropheModIconItem;
import net.mcreator.catastrophemod.item.CalicoMushroomStewItem;
import net.mcreator.catastrophemod.item.CactusCutterItem;
import net.mcreator.catastrophemod.item.BulletShellItem;
import net.mcreator.catastrophemod.item.BlossomFloraItem;
import net.mcreator.catastrophemod.item.BlizzardItem;
import net.mcreator.catastrophemod.item.BeetleCallerItem;
import net.mcreator.catastrophemod.item.BackPackItem;
import net.mcreator.catastrophemod.item.AxeMasteryCrestItem;
import net.mcreator.catastrophemod.item.AtlanticSeaNettleItemItem;
import net.mcreator.catastrophemod.item.AssassinsGloryItem;
import net.mcreator.catastrophemod.item.AmuletOfWeakeningItem;
import net.mcreator.catastrophemod.item.AmuletOfVitalityItem;
import net.mcreator.catastrophemod.item.AeroBootsItem;
import net.mcreator.catastrophemod.item.AcidTarantulaItem;
import net.mcreator.catastrophemod.item.AccursedTomeItem;
import net.mcreator.catastrophemod.CatastropheModMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class CatastropheModModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, CatastropheModMod.MODID);
	public static final RegistryObject<Item> WOODEN_KATANA = REGISTRY.register("wooden_katana", () -> new WoodenKatanaItem());
	public static final RegistryObject<Item> REINFORCED_IRON_ARMOR_HELMET = REGISTRY.register("reinforced_iron_armor_helmet", () -> new Reinforced_IronArmorItem.Helmet());
	public static final RegistryObject<Item> REINFORCED_IRON_ARMOR_CHESTPLATE = REGISTRY.register("reinforced_iron_armor_chestplate", () -> new Reinforced_IronArmorItem.Chestplate());
	public static final RegistryObject<Item> REINFORCED_IRON_ARMOR_LEGGINGS = REGISTRY.register("reinforced_iron_armor_leggings", () -> new Reinforced_IronArmorItem.Leggings());
	public static final RegistryObject<Item> REINFORCED_IRON_ARMOR_BOOTS = REGISTRY.register("reinforced_iron_armor_boots", () -> new Reinforced_IronArmorItem.Boots());
	public static final RegistryObject<Item> ICE_SWORD = REGISTRY.register("ice_sword", () -> new IceSwordItem());
	public static final RegistryObject<Item> CALICO_MUSHROOM = block(CatastropheModModBlocks.CALICO_MUSHROOM);
	public static final RegistryObject<Item> COPPER_SHARD = REGISTRY.register("copper_shard", () -> new CopperShardItem());
	public static final RegistryObject<Item> POISONED_IRON_HEART = REGISTRY.register("poisoned_iron_heart", () -> new PoisonedIronHeartItem());
	public static final RegistryObject<Item> POISONED_VINES = REGISTRY.register("poisoned_vines", () -> new PoisonedVinesItem());
	public static final RegistryObject<Item> SPELL_TOME = REGISTRY.register("spell_tome", () -> new SpellTomeItem());
	public static final RegistryObject<Item> BACK_PACK = REGISTRY.register("back_pack", () -> new BackPackItem());
	public static final RegistryObject<Item> NATUREITE_INGOT = REGISTRY.register("natureite_ingot", () -> new NatureiteIngotItem());
	public static final RegistryObject<Item> NATUREITE_ORE = block(CatastropheModModBlocks.NATUREITE_ORE);
	public static final RegistryObject<Item> NATUREITE_BLOCK = block(CatastropheModModBlocks.NATUREITE_BLOCK);
	public static final RegistryObject<Item> NATUREITE_PICKAXE = REGISTRY.register("natureite_pickaxe", () -> new NatureitePickaxeItem());
	public static final RegistryObject<Item> NATUREITE_AXE = REGISTRY.register("natureite_axe", () -> new NatureiteAxeItem());
	public static final RegistryObject<Item> NATUREITE_SWORD = REGISTRY.register("natureite_sword", () -> new NatureiteSwordItem());
	public static final RegistryObject<Item> NATUREITE_SHOVEL = REGISTRY.register("natureite_shovel", () -> new NatureiteShovelItem());
	public static final RegistryObject<Item> NATUREITE_HOE = REGISTRY.register("natureite_hoe", () -> new NatureiteHoeItem());
	public static final RegistryObject<Item> NATUREITE_ARMOR_HELMET = REGISTRY.register("natureite_armor_helmet", () -> new NatureiteArmorItem.Helmet());
	public static final RegistryObject<Item> NATUREITE_ARMOR_CHESTPLATE = REGISTRY.register("natureite_armor_chestplate", () -> new NatureiteArmorItem.Chestplate());
	public static final RegistryObject<Item> NATUREITE_ARMOR_LEGGINGS = REGISTRY.register("natureite_armor_leggings", () -> new NatureiteArmorItem.Leggings());
	public static final RegistryObject<Item> NATUREITE_ARMOR_BOOTS = REGISTRY.register("natureite_armor_boots", () -> new NatureiteArmorItem.Boots());
	public static final RegistryObject<Item> SPELL_OF_FLAMES = REGISTRY.register("spell_of_flames", () -> new SpellOfFlamesItem());
	public static final RegistryObject<Item> MINERAL_WRAITH_LOOT_BUNDLE = REGISTRY.register("mineral_wraith_loot_bundle", () -> new MineralWraithLootBundleItem());
	public static final RegistryObject<Item> THORN_INFESTED_ARMOR_LOOT_BUNDLE = REGISTRY.register("thorn_infested_armor_loot_bundle", () -> new ThornInfestedArmorLootBundleItem());
	public static final RegistryObject<Item> SPELLOF_LIGHTNING = REGISTRY.register("spellof_lightning", () -> new SpellofLightningItem());
	public static final RegistryObject<Item> ELECTRIFIED_COPPER_SWORD = REGISTRY.register("electrified_copper_sword", () -> new ElectrifiedCopperSwordItem());
	public static final RegistryObject<Item> SPELLOF_POISON = REGISTRY.register("spellof_poison", () -> new SpellofPoisonItem());
	public static final RegistryObject<Item> ROSXITE_INGOT = REGISTRY.register("rosxite_ingot", () -> new RosxiteIngotItem());
	public static final RegistryObject<Item> NATURES_BLESSING_HELMET = REGISTRY.register("natures_blessing_helmet", () -> new NaturesBlessingItem.Helmet());
	public static final RegistryObject<Item> NATURES_BLESSING_CHESTPLATE = REGISTRY.register("natures_blessing_chestplate", () -> new NaturesBlessingItem.Chestplate());
	public static final RegistryObject<Item> NATURES_BLESSING_LEGGINGS = REGISTRY.register("natures_blessing_leggings", () -> new NaturesBlessingItem.Leggings());
	public static final RegistryObject<Item> NATURES_BLESSING_BOOTS = REGISTRY.register("natures_blessing_boots", () -> new NaturesBlessingItem.Boots());
	public static final RegistryObject<Item> RAW_NATUREITE = REGISTRY.register("raw_natureite", () -> new RawNatureiteItem());
	public static final RegistryObject<Item> ORBITAL_BARRAGE = REGISTRY.register("orbital_barrage", () -> new OrbitalBarrageItem());
	public static final RegistryObject<Item> STORM_BOW = REGISTRY.register("storm_bow", () -> new StormBowItem());
	public static final RegistryObject<Item> MUSIC_DISC_STRIKE_YOU_DOWN = REGISTRY.register("music_disc_strike_you_down", () -> new MusicDiscStrikeYouDownItem());
	public static final RegistryObject<Item> NATURES_STRIKE = REGISTRY.register("natures_strike", () -> new NaturesStrikeItem());
	public static final RegistryObject<Item> NATUREITE_APPLE = REGISTRY.register("natureite_apple", () -> new NatureiteAppleItem());
	public static final RegistryObject<Item> GLOVEOFTHE_DESERTS = REGISTRY.register("gloveofthe_deserts", () -> new GloveoftheDesertsItem());
	public static final RegistryObject<Item> LIVING_MOSS = REGISTRY.register("living_moss", () -> new LivingMossItem());
	public static final RegistryObject<Item> REINFORCED_PLATES = REGISTRY.register("reinforced_plates", () -> new ReinforcedPlatesItem());
	public static final RegistryObject<Item> DRIED_ROSXITE_ORE = block(CatastropheModModBlocks.DRIED_ROSXITE_ORE);
	public static final RegistryObject<Item> RAW_ROSXITE = REGISTRY.register("raw_rosxite", () -> new RawRosxiteItem());
	public static final RegistryObject<Item> ROSXITE_ORE = block(CatastropheModModBlocks.ROSXITE_ORE);
	public static final RegistryObject<Item> ASSASSIN_SKELETON_SPAWN_EGG = REGISTRY.register("assassin_skeleton_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.ASSASSIN_SKELETON, -1, -7602176, new Item.Properties()));
	public static final RegistryObject<Item> STORM_SHIELD = REGISTRY.register("storm_shield", () -> new StormShieldItem());
	public static final RegistryObject<Item> RUNNING_BOOTS = REGISTRY.register("running_boots", () -> new RunningBootsItem());
	public static final RegistryObject<Item> POCKET_SHIELD_GENERATOR = REGISTRY.register("pocket_shield_generator", () -> new PocketShieldGeneratorItem());
	public static final RegistryObject<Item> ACID_TARANTULA = REGISTRY.register("acid_tarantula", () -> new AcidTarantulaItem());
	public static final RegistryObject<Item> CRIMSON_DAGGER = REGISTRY.register("crimson_dagger", () -> new CrimsonDaggerItem());
	public static final RegistryObject<Item> NETHERITE_SHIELD = REGISTRY.register("netherite_shield", () -> new NetheriteShieldItem());
	public static final RegistryObject<Item> GOLDEN_BRACELET = REGISTRY.register("golden_bracelet", () -> new GoldenBraceletItem());
	public static final RegistryObject<Item> NETHER_TREADS = REGISTRY.register("nether_treads", () -> new NetherTreadsItem());
	public static final RegistryObject<Item> SEA_PENDANT = REGISTRY.register("sea_pendant", () -> new SeaPendantItem());
	public static final RegistryObject<Item> ASSASSINS_GLORY = REGISTRY.register("assassins_glory", () -> new AssassinsGloryItem());
	public static final RegistryObject<Item> MUSIC_DISC_PROLIFERATING_MUSHROOMS = REGISTRY.register("music_disc_proliferating_mushrooms", () -> new MusicDiscProliferatingMushroomsItem());
	public static final RegistryObject<Item> MUSIC_DISC_OVERGROWN_GROVE = REGISTRY.register("music_disc_overgrown_grove", () -> new MusicDiscOvergrownGroveItem());
	public static final RegistryObject<Item> MUSIC_DISC_NETHERS_FURY = REGISTRY.register("music_disc_nethers_fury", () -> new MusicDiscNethersFuryItem());
	public static final RegistryObject<Item> FREEZING_STAFF = REGISTRY.register("freezing_staff", () -> new FreezingStaffItem());
	public static final RegistryObject<Item> SPELL_OF_PHANTOMS = REGISTRY.register("spell_of_phantoms", () -> new SpellOfPhantomsItem());
	public static final RegistryObject<Item> THORN_BOW = REGISTRY.register("thorn_bow", () -> new ThornBowItem());
	public static final RegistryObject<Item> NATURITE_BOW = REGISTRY.register("naturite_bow", () -> new NaturiteBowItem());
	public static final RegistryObject<Item> CALICO_SHROOM = block(CatastropheModModBlocks.CALICO_SHROOM);
	public static final RegistryObject<Item> TALL_CALICO_SHROOM = block(CatastropheModModBlocks.TALL_CALICO_SHROOM);
	public static final RegistryObject<Item> CALICO_MUSHROOM_STEW = REGISTRY.register("calico_mushroom_stew", () -> new CalicoMushroomStewItem());
	public static final RegistryObject<Item> PURIFIED_CALICO_MUSHROOM_STEW = REGISTRY.register("purified_calico_mushroom_stew", () -> new PurifiedCalicoMushroomStewItem());
	public static final RegistryObject<Item> MUSIC_DISC_ENLIGHTENED_STARLIGHT = REGISTRY.register("music_disc_enlightened_starlight", () -> new MusicDiscEnlightenedStarlightItem());
	public static final RegistryObject<Item> MUSIC_DISC_OUTSIDE_OF_THE_ATMOSPHERE = REGISTRY.register("music_disc_outside_of_the_atmosphere", () -> new MusicDiscOutsideOfTheAtmosphereItem());
	public static final RegistryObject<Item> SHROOMIUM_ORE = block(CatastropheModModBlocks.SHROOMIUM_ORE);
	public static final RegistryObject<Item> RAW_SHROOMIUM = REGISTRY.register("raw_shroomium", () -> new RawShroomiumItem());
	public static final RegistryObject<Item> SHROOMIUM_INGOT = REGISTRY.register("shroomium_ingot", () -> new ShroomiumIngotItem());
	public static final RegistryObject<Item> SHROOMIUM_HELMET = REGISTRY.register("shroomium_helmet", () -> new ShroomiumItem.Helmet());
	public static final RegistryObject<Item> SHROOMIUM_CHESTPLATE = REGISTRY.register("shroomium_chestplate", () -> new ShroomiumItem.Chestplate());
	public static final RegistryObject<Item> SHROOMIUM_LEGGINGS = REGISTRY.register("shroomium_leggings", () -> new ShroomiumItem.Leggings());
	public static final RegistryObject<Item> SHROOMIUM_BOOTS = REGISTRY.register("shroomium_boots", () -> new ShroomiumItem.Boots());
	public static final RegistryObject<Item> CACTUS_CUTTER = REGISTRY.register("cactus_cutter", () -> new CactusCutterItem());
	public static final RegistryObject<Item> WOODEN_SPEAR = REGISTRY.register("wooden_spear", () -> new WoodenSpearItem());
	public static final RegistryObject<Item> STONE_SPEAR = REGISTRY.register("stone_spear", () -> new StoneSpearItem());
	public static final RegistryObject<Item> IRON_SPEAR = REGISTRY.register("iron_spear", () -> new IronSpearItem());
	public static final RegistryObject<Item> GOLDEN_SPEAR = REGISTRY.register("golden_spear", () -> new GoldenSpearItem());
	public static final RegistryObject<Item> DIAMOND_SPEAR = REGISTRY.register("diamond_spear", () -> new DiamondSpearItem());
	public static final RegistryObject<Item> NETHERITE_SPEAR = REGISTRY.register("netherite_spear", () -> new NetheriteSpearItem());
	public static final RegistryObject<Item> NATURITE_SPEAR = REGISTRY.register("naturite_spear", () -> new NaturiteSpearItem());
	public static final RegistryObject<Item> SPEAR_OF_NATURE = REGISTRY.register("spear_of_nature", () -> new SpearOfNatureItem());
	public static final RegistryObject<Item> ELECTRIFIED_SPEAR = REGISTRY.register("electrified_spear", () -> new ElectrifiedSpearItem());
	public static final RegistryObject<Item> MOSS_HELMET = REGISTRY.register("moss_helmet", () -> new MossItem.Helmet());
	public static final RegistryObject<Item> MOSS_CHESTPLATE = REGISTRY.register("moss_chestplate", () -> new MossItem.Chestplate());
	public static final RegistryObject<Item> MOSS_LEGGINGS = REGISTRY.register("moss_leggings", () -> new MossItem.Leggings());
	public static final RegistryObject<Item> MOSS_BOOTS = REGISTRY.register("moss_boots", () -> new MossItem.Boots());
	public static final RegistryObject<Item> SPIRIT_IN_A_BOTTLE = REGISTRY.register("spirit_in_a_bottle", () -> new SpiritInABottleItem());
	public static final RegistryObject<Item> SEA_SPEAR = REGISTRY.register("sea_spear", () -> new SeaSpearItem());
	public static final RegistryObject<Item> SEA_PICKAXE = REGISTRY.register("sea_pickaxe", () -> new SeaPickaxeItem());
	public static final RegistryObject<Item> SEA_AXE = REGISTRY.register("sea_axe", () -> new SeaAxeItem());
	public static final RegistryObject<Item> SEA_SWORD = REGISTRY.register("sea_sword", () -> new SeaSwordItem());
	public static final RegistryObject<Item> SEA_SHOVEL = REGISTRY.register("sea_shovel", () -> new SeaShovelItem());
	public static final RegistryObject<Item> SEA_HOE = REGISTRY.register("sea_hoe", () -> new SeaHoeItem());
	public static final RegistryObject<Item> NAUTILUS_HELMET = REGISTRY.register("nautilus_helmet", () -> new NautilusItem.Helmet());
	public static final RegistryObject<Item> NAUTILUS_CHESTPLATE = REGISTRY.register("nautilus_chestplate", () -> new NautilusItem.Chestplate());
	public static final RegistryObject<Item> NAUTILUS_LEGGINGS = REGISTRY.register("nautilus_leggings", () -> new NautilusItem.Leggings());
	public static final RegistryObject<Item> NAUTILUS_BOOTS = REGISTRY.register("nautilus_boots", () -> new NautilusItem.Boots());
	public static final RegistryObject<Item> RIPTIDE = REGISTRY.register("riptide", () -> new RiptideItem());
	public static final RegistryObject<Item> HERMIT_CRAB_SPAWN_EGG = REGISTRY.register("hermit_crab_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.HERMIT_CRAB, -3851231, -3360344, new Item.Properties()));
	public static final RegistryObject<Item> TEAR_OF_THE_SEA = REGISTRY.register("tear_of_the_sea", () -> new TearOfTheSeaItem());
	public static final RegistryObject<Item> SEA_BOW = REGISTRY.register("sea_bow", () -> new SeaBowItem());
	public static final RegistryObject<Item> OCEANIC_ARTIFACT = REGISTRY.register("oceanic_artifact", () -> new OceanicArtifactItem());
	public static final RegistryObject<Item> HUNTER_HELMET = REGISTRY.register("hunter_helmet", () -> new HunterItem.Helmet());
	public static final RegistryObject<Item> HUNTER_CHESTPLATE = REGISTRY.register("hunter_chestplate", () -> new HunterItem.Chestplate());
	public static final RegistryObject<Item> HUNTER_LEGGINGS = REGISTRY.register("hunter_leggings", () -> new HunterItem.Leggings());
	public static final RegistryObject<Item> HUNTER_BOOTS = REGISTRY.register("hunter_boots", () -> new HunterItem.Boots());
	public static final RegistryObject<Item> MANA_ROSE_PLANT = block(CatastropheModModBlocks.MANA_ROSE_PLANT);
	public static final RegistryObject<Item> MANA_ROSE = REGISTRY.register("mana_rose", () -> new ManaRoseItem());
	public static final RegistryObject<Item> QUIVER = REGISTRY.register("quiver", () -> new QuiverItem());
	public static final RegistryObject<Item> REINFORCED_SHIELD = REGISTRY.register("reinforced_shield", () -> new ReinforcedShieldItem());
	public static final RegistryObject<Item> LIGHTNING_BLADE_STAFF = REGISTRY.register("lightning_blade_staff", () -> new LightningBladeStaffItem());
	public static final RegistryObject<Item> MARKSMANS_CREST = REGISTRY.register("marksmans_crest", () -> new MarksmansCrestItem());
	public static final RegistryObject<Item> AMULET_OF_VITALITY = REGISTRY.register("amulet_of_vitality", () -> new AmuletOfVitalityItem());
	public static final RegistryObject<Item> SPORE_ZOMBIE_SPAWN_EGG = REGISTRY.register("spore_zombie_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.SPORE_ZOMBIE, -1056589, -1075909, new Item.Properties()));
	public static final RegistryObject<Item> KNIFE_OF_PROFICIENCY = REGISTRY.register("knife_of_proficiency", () -> new KnifeOfProficiencyItem());
	public static final RegistryObject<Item> SANDSTORM_SURGE = REGISTRY.register("sandstorm_surge", () -> new SandstormSurgeItem());
	public static final RegistryObject<Item> IRON_ROUND = REGISTRY.register("iron_round", () -> new IronRoundItem());
	public static final RegistryObject<Item> BULLET_SHELL = REGISTRY.register("bullet_shell", () -> new BulletShellItem());
	public static final RegistryObject<Item> CHISELED_CHARRED_BRICKS = block(CatastropheModModBlocks.CHISELED_CHARRED_BRICKS);
	public static final RegistryObject<Item> CHARRED_BRICKS = block(CatastropheModModBlocks.CHARRED_BRICKS);
	public static final RegistryObject<Item> CRACKED_CHARRED_BRICKS = block(CatastropheModModBlocks.CRACKED_CHARRED_BRICKS);
	public static final RegistryObject<Item> POLISHED_CHARRED_STONE = block(CatastropheModModBlocks.POLISHED_CHARRED_STONE);
	public static final RegistryObject<Item> CHARRED_TILES = block(CatastropheModModBlocks.CHARRED_TILES);
	public static final RegistryObject<Item> CHARRED_STONE = block(CatastropheModModBlocks.CHARRED_STONE);
	public static final RegistryObject<Item> CHARRED_STONE_SLAB = block(CatastropheModModBlocks.CHARRED_STONE_SLAB);
	public static final RegistryObject<Item> CHARRED_STONE_STAIRS = block(CatastropheModModBlocks.CHARRED_STONE_STAIRS);
	public static final RegistryObject<Item> CHARRED_BRICKS_SLAB = block(CatastropheModModBlocks.CHARRED_BRICKS_SLAB);
	public static final RegistryObject<Item> CHARRED_BRICKS_STAIRS = block(CatastropheModModBlocks.CHARRED_BRICKS_STAIRS);
	public static final RegistryObject<Item> CHARRED_TILES_SLAB = block(CatastropheModModBlocks.CHARRED_TILES_SLAB);
	public static final RegistryObject<Item> CHARRED_TILES_STAIRS = block(CatastropheModModBlocks.CHARRED_TILES_STAIRS);
	public static final RegistryObject<Item> THORN_SWORD = REGISTRY.register("thorn_sword", () -> new ThornSwordItem());
	public static final RegistryObject<Item> CALICO_STAG_BEETLE_SPAWN_EGG = REGISTRY.register("calico_stag_beetle_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.CALICO_STAG_BEETLE, -1559, -7767447, new Item.Properties()));
	public static final RegistryObject<Item> NATURE_DEFENDER = REGISTRY.register("nature_defender", () -> new NatureDefenderItem());
	public static final RegistryObject<Item> DECAYING_GRASS = block(CatastropheModModBlocks.DECAYING_GRASS);
	public static final RegistryObject<Item> DECAYING_SHALE = block(CatastropheModModBlocks.DECAYING_SHALE);
	public static final RegistryObject<Item> DECAYING_SPINE = block(CatastropheModModBlocks.DECAYING_SPINE);
	public static final RegistryObject<Item> FLOWER_OF_AFFLICTION = block(CatastropheModModBlocks.FLOWER_OF_AFFLICTION);
	public static final RegistryObject<Item> WITHERING_GRASS = block(CatastropheModModBlocks.WITHERING_GRASS);
	public static final RegistryObject<Item> TALL_WITHERING_GRASS = doubleBlock(CatastropheModModBlocks.TALL_WITHERING_GRASS);
	public static final RegistryObject<Item> ROD_OF_TELEPORTATION = REGISTRY.register("rod_of_teleportation", () -> new RodOfTeleportationItem());
	public static final RegistryObject<Item> BEETLE_CALLER = REGISTRY.register("beetle_caller", () -> new BeetleCallerItem());
	public static final RegistryObject<Item> SHADE_SPAWN_EGG = REGISTRY.register("shade_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.SHADE, -15856114, -14672338, new Item.Properties()));
	public static final RegistryObject<Item> CRYSTAL_ROUND = REGISTRY.register("crystal_round", () -> new CrystalRoundItem());
	public static final RegistryObject<Item> ELECTRIFIED_ROUND = REGISTRY.register("electrified_round", () -> new ElectrifiedRoundItem());
	public static final RegistryObject<Item> VENOMOUS_ROUND = REGISTRY.register("venomous_round", () -> new VenomousRoundItem());
	public static final RegistryObject<Item> SEA_CONCH = REGISTRY.register("sea_conch", () -> new SeaConchItem());
	public static final RegistryObject<Item> NATURE_BLESSED_SPIRIT_STAFF = REGISTRY.register("nature_blessed_spirit_staff", () -> new NatureBlessedSpiritStaffItem());
	public static final RegistryObject<Item> AERO_BOOTS = REGISTRY.register("aero_boots", () -> new AeroBootsItem());
	public static final RegistryObject<Item> MUSIC_DISC_VINES_OF_VENOM = REGISTRY.register("music_disc_vines_of_venom", () -> new MusicDiscVinesOfVenomItem());
	public static final RegistryObject<Item> LEATHER_GLOVE = REGISTRY.register("leather_glove", () -> new LeatherGloveItem());
	public static final RegistryObject<Item> FIREBRAND = REGISTRY.register("firebrand", () -> new FirebrandItem());
	public static final RegistryObject<Item> GRAVE_DIGGER = REGISTRY.register("grave_digger", () -> new GraveDiggerItem());
	public static final RegistryObject<Item> COPPER_TOKEN = REGISTRY.register("copper_token", () -> new CopperTokenItem());
	public static final RegistryObject<Item> WHISPERS_CURSE = REGISTRY.register("whispers_curse", () -> new WhispersCurseItem());
	public static final RegistryObject<Item> REINFORCED_AXE = REGISTRY.register("reinforced_axe", () -> new ReinforcedAxeItem());
	public static final RegistryObject<Item> MOLTEN_CHARRED_BRICKS = block(CatastropheModModBlocks.MOLTEN_CHARRED_BRICKS);
	public static final RegistryObject<Item> POLISHED_CHARRED_STONE_STAIRS = block(CatastropheModModBlocks.POLISHED_CHARRED_STONE_STAIRS);
	public static final RegistryObject<Item> POLISHED_CHARRED_STONE_SLAB = block(CatastropheModModBlocks.POLISHED_CHARRED_STONE_SLAB);
	public static final RegistryObject<Item> MOLTEN_CHARRED_BRICKS_STAIRS = block(CatastropheModModBlocks.MOLTEN_CHARRED_BRICKS_STAIRS);
	public static final RegistryObject<Item> MOLTEN_CHARRED_BRICKS_SLAB = block(CatastropheModModBlocks.MOLTEN_CHARRED_BRICKS_SLAB);
	public static final RegistryObject<Item> CRIMSON_RAY = REGISTRY.register("crimson_ray", () -> new CrimsonRayItem());
	public static final RegistryObject<Item> THORN_HELMET = REGISTRY.register("thorn_helmet", () -> new ThornItem.Helmet());
	public static final RegistryObject<Item> THORN_CHESTPLATE = REGISTRY.register("thorn_chestplate", () -> new ThornItem.Chestplate());
	public static final RegistryObject<Item> THORN_LEGGINGS = REGISTRY.register("thorn_leggings", () -> new ThornItem.Leggings());
	public static final RegistryObject<Item> THORN_BOOTS = REGISTRY.register("thorn_boots", () -> new ThornItem.Boots());
	public static final RegistryObject<Item> SPORE_STAFF = REGISTRY.register("spore_staff", () -> new SporeStaffItem());
	public static final RegistryObject<Item> SPORESPLOSION = REGISTRY.register("sporesplosion", () -> new SporesplosionItem());
	public static final RegistryObject<Item> FROZEN_SHIELD = REGISTRY.register("frozen_shield", () -> new FrozenShieldItem());
	public static final RegistryObject<Item> SHADOWFLAME_WHISPER = REGISTRY.register("shadowflame_whisper", () -> new ShadowflameWhisperItem());
	public static final RegistryObject<Item> SHADOWFLAME_BURSTER = REGISTRY.register("shadowflame_burster", () -> new ShadowflameBursterItem());
	public static final RegistryObject<Item> SHADOWFLAME_SCEPTER = REGISTRY.register("shadowflame_scepter", () -> new ShadowflameScepterItem());
	public static final RegistryObject<Item> ICE_BOW = REGISTRY.register("ice_bow", () -> new IceBowItem());
	public static final RegistryObject<Item> ICE_SPEAR = REGISTRY.register("ice_spear", () -> new IceSpearItem());
	public static final RegistryObject<Item> SHROOM_BOW = REGISTRY.register("shroom_bow", () -> new ShroomBowItem());
	public static final RegistryObject<Item> CHARRED_SKELETON_GUARD_SPAWN_EGG = REGISTRY.register("charred_skeleton_guard_spawn_egg",
			() -> new ForgeSpawnEggItem(CatastropheModModEntities.CHARRED_SKELETON_GUARD, -14606047, -367075, new Item.Properties()));
	public static final RegistryObject<Item> CRYSTAL_SPEAR = REGISTRY.register("crystal_spear", () -> new CrystalSpearItem());
	public static final RegistryObject<Item> SPEARTHE_GUNGNIR = REGISTRY.register("spearthe_gungnir", () -> new SpeartheGungnirItem());
	public static final RegistryObject<Item> STAFFOF_VITALITY = REGISTRY.register("staffof_vitality", () -> new StaffofVitalityItem());
	public static final RegistryObject<Item> SEPULCHER_LOOT_BUNDLE = REGISTRY.register("sepulcher_loot_bundle", () -> new SepulcherLootBundleItem());
	public static final RegistryObject<Item> HEART_OF_THORNS = REGISTRY.register("heart_of_thorns", () -> new HeartOfThornsItem());
	public static final RegistryObject<Item> STAFF_OF_THORNS = REGISTRY.register("staff_of_thorns", () -> new StaffOfThornsItem());
	public static final RegistryObject<Item> INFERNAL_FRAGMENT = REGISTRY.register("infernal_fragment", () -> new InfernalFragmentItem());
	public static final RegistryObject<Item> SHADOWFLAME_FRAGMENT = REGISTRY.register("shadowflame_fragment", () -> new ShadowflameFragmentItem());
	public static final RegistryObject<Item> CRIMSTONE_GEM = REGISTRY.register("crimstone_gem", () -> new CrimstoneGemItem());
	public static final RegistryObject<Item> CRIMSTONE_ORE = block(CatastropheModModBlocks.CRIMSTONE_ORE);
	public static final RegistryObject<Item> HELLBANE = REGISTRY.register("hellbane", () -> new HellbaneItem());
	public static final RegistryObject<Item> CRYSTAL_BOW = REGISTRY.register("crystal_bow", () -> new CrystalBowItem());
	public static final RegistryObject<Item> BLAZING_PHOENIX_SPAWN_EGG = REGISTRY.register("blazing_phoenix_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.BLAZING_PHOENIX, -1732864, -14799, new Item.Properties()));
	public static final RegistryObject<Item> BLOSSOM_FLORA = REGISTRY.register("blossom_flora", () -> new BlossomFloraItem());
	public static final RegistryObject<Item> EARTH_BREAKER = REGISTRY.register("earth_breaker", () -> new EarthBreakerItem());
	public static final RegistryObject<Item> EARTHBOUND_STAFF = REGISTRY.register("earthbound_staff", () -> new EarthboundStaffItem());
	public static final RegistryObject<Item> EARTH_SHATTERER = REGISTRY.register("earth_shatterer", () -> new EarthShattererItem());
	public static final RegistryObject<Item> EARTH_GAUNTLET = REGISTRY.register("earth_gauntlet", () -> new EarthGauntletItem());
	public static final RegistryObject<Item> EARTHBOUND_WRAITH_LOOT_BUNDLE = REGISTRY.register("earthbound_wraith_loot_bundle", () -> new EarthboundWraithLootBundleItem());
	public static final RegistryObject<Item> PACIFYING_SIGHT = REGISTRY.register("pacifying_sight", () -> new PacifyingSightItem());
	public static final RegistryObject<Item> AMULET_OF_WEAKENING = REGISTRY.register("amulet_of_weakening", () -> new AmuletOfWeakeningItem());
	public static final RegistryObject<Item> THUNDER_STAR = REGISTRY.register("thunder_star", () -> new ThunderStarItem());
	public static final RegistryObject<Item> STORM_CATALYST = REGISTRY.register("storm_catalyst", () -> new StormCatalystItem());
	public static final RegistryObject<Item> LIFEPIERCER = REGISTRY.register("lifepiercer", () -> new LifepiercerItem());
	public static final RegistryObject<Item> LIFEPIERCER_0 = REGISTRY.register("lifepiercer_0", () -> new Lifepiercer0Item());
	public static final RegistryObject<Item> LIFEPIERCER_1 = REGISTRY.register("lifepiercer_1", () -> new Lifepiercer1Item());
	public static final RegistryObject<Item> LIFEPIERCER_2 = REGISTRY.register("lifepiercer_2", () -> new Lifepiercer2Item());
	public static final RegistryObject<Item> VEIN_STRIKER = REGISTRY.register("vein_striker", () -> new VeinStrikerItem());
	public static final RegistryObject<Item> FLAMESTRIKE = REGISTRY.register("flamestrike", () -> new FlamestrikeItem());
	public static final RegistryObject<Item> WITHER_SKULL_FRAGMENT = REGISTRY.register("wither_skull_fragment", () -> new WitherSkullFragmentItem());
	public static final RegistryObject<Item> SHADOWFLAME_SKULL = REGISTRY.register("shadowflame_skull", () -> new ShadowflameSkullItem());
	public static final RegistryObject<Item> MUSIC_DISC_BATTLE_OF_STONE = REGISTRY.register("music_disc_battle_of_stone", () -> new MusicDiscBattleOfStoneItem());
	public static final RegistryObject<Item> EARTHBOUND_CORE = REGISTRY.register("earthbound_core", () -> new EarthboundCoreItem());
	public static final RegistryObject<Item> MUSIC_DISC_SPARK_OF_A_SHADOW = REGISTRY.register("music_disc_spark_of_a_shadow", () -> new MusicDiscSparkOfAShadowItem());
	public static final RegistryObject<Item> CATASTROPHE_MOD_ICON = REGISTRY.register("catastrophe_mod_icon", () -> new CatastropheModIconItem());
	public static final RegistryObject<Item> NIGHTFALLS_DEMISE = REGISTRY.register("nightfalls_demise", () -> new NightfallsDemiseItem());
	public static final RegistryObject<Item> CRYSTALLINE_EDGE = REGISTRY.register("crystalline_edge", () -> new CrystallineEdgeItem());
	public static final RegistryObject<Item> STAR = REGISTRY.register("star", () -> new StarItem());
	public static final RegistryObject<Item> MANA_STAR = REGISTRY.register("mana_star", () -> new ManaStarItem());
	public static final RegistryObject<Item> LESSER_MANA_POTION = REGISTRY.register("lesser_mana_potion", () -> new LesserManaPotionItem());
	public static final RegistryObject<Item> MANA_POTION = REGISTRY.register("mana_potion", () -> new ManaPotionItem());
	public static final RegistryObject<Item> CURSED_CLOTH = REGISTRY.register("cursed_cloth", () -> new CursedClothItem());
	public static final RegistryObject<Item> CURSED_ARMOR_HELMET = REGISTRY.register("cursed_armor_helmet", () -> new CursedArmorItem.Helmet());
	public static final RegistryObject<Item> CURSED_ARMOR_CHESTPLATE = REGISTRY.register("cursed_armor_chestplate", () -> new CursedArmorItem.Chestplate());
	public static final RegistryObject<Item> CURSED_ARMOR_LEGGINGS = REGISTRY.register("cursed_armor_leggings", () -> new CursedArmorItem.Leggings());
	public static final RegistryObject<Item> CURSED_ARMOR_BOOTS = REGISTRY.register("cursed_armor_boots", () -> new CursedArmorItem.Boots());
	public static final RegistryObject<Item> SEA_CRYSTAL_BLOCK = block(CatastropheModModBlocks.SEA_CRYSTAL_BLOCK);
	public static final RegistryObject<Item> SEA_CRYSTAL_CLUSTER = block(CatastropheModModBlocks.SEA_CRYSTAL_CLUSTER);
	public static final RegistryObject<Item> RING_OF_RESILIENCE = REGISTRY.register("ring_of_resilience", () -> new RingOfResilienceItem());
	public static final RegistryObject<Item> RIPSAW = REGISTRY.register("ripsaw", () -> new RipsawItem());
	public static final RegistryObject<Item> DIAMOND_DETONATION = REGISTRY.register("diamond_detonation", () -> new DiamondDetonationItem());
	public static final RegistryObject<Item> SILK_MOTH_SPAWN_EGG = REGISTRY.register("silk_moth_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.SILK_MOTH, -2042682, -11454426, new Item.Properties()));
	public static final RegistryObject<Item> ROTTEN_HEART = REGISTRY.register("rotten_heart", () -> new RottenHeartItem());
	public static final RegistryObject<Item> ATLANTIC_SEA_NETTLE_SPAWN_EGG = REGISTRY.register("atlantic_sea_nettle_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.ATLANTIC_SEA_NETTLE, -1738012, -7329574, new Item.Properties()));
	public static final RegistryObject<Item> STORM_ARROW = REGISTRY.register("storm_arrow", () -> new StormArrowItem());
	public static final RegistryObject<Item> BLIZZARD = REGISTRY.register("blizzard", () -> new BlizzardItem());
	public static final RegistryObject<Item> ANGLERFISH_SPAWN_EGG = REGISTRY.register("anglerfish_spawn_egg", () -> new ForgeSpawnEggItem(CatastropheModModEntities.ANGLERFISH, -5214389, -13605228, new Item.Properties()));
	public static final RegistryObject<Item> SCREENSHAKE_TEST_ITEM = REGISTRY.register("screenshake_test_item", () -> new ScreenshakeTestItemItem());
	public static final RegistryObject<Item> NATURITE_SHIELD = REGISTRY.register("naturite_shield", () -> new NaturiteShieldItem());
	public static final RegistryObject<Item> AXE_MASTERY_CREST = REGISTRY.register("axe_mastery_crest", () -> new AxeMasteryCrestItem());
	public static final RegistryObject<Item> ACCURSED_TOME = REGISTRY.register("accursed_tome", () -> new AccursedTomeItem());
	public static final RegistryObject<Item> SWORD_MASTERY_CREST = REGISTRY.register("sword_mastery_crest", () -> new SwordMasteryCrestItem());
	public static final RegistryObject<Item> SPEAR_MASTERY_CREST = REGISTRY.register("spear_mastery_crest", () -> new SpearMasteryCrestItem());
	public static final RegistryObject<Item> RUSTGUN = REGISTRY.register("rustgun", () -> new RustgunItem());
	public static final RegistryObject<Item> RUSTY_COGWHEEL = REGISTRY.register("rusty_cogwheel", () -> new RustyCogwheelItem());
	public static final RegistryObject<Item> DEPTHSTONE = block(CatastropheModModBlocks.DEPTHSTONE);
	public static final RegistryObject<Item> DEPTHSTONE_BRICKS = block(CatastropheModModBlocks.DEPTHSTONE_BRICKS);
	public static final RegistryObject<Item> CRACKED_DEPTHSTONE_BRICKS = block(CatastropheModModBlocks.CRACKED_DEPTHSTONE_BRICKS);
	public static final RegistryObject<Item> CHISELED_DEPTHSTONE_BRICKS = block(CatastropheModModBlocks.CHISELED_DEPTHSTONE_BRICKS);
	public static final RegistryObject<Item> DEPTHSTONE_SLAB = block(CatastropheModModBlocks.DEPTHSTONE_SLAB);
	public static final RegistryObject<Item> DEPTHSTONE_STAIRS = block(CatastropheModModBlocks.DEPTHSTONE_STAIRS);
	public static final RegistryObject<Item> DEPTHSTONE_BRICKS_SLAB = block(CatastropheModModBlocks.DEPTHSTONE_BRICKS_SLAB);
	public static final RegistryObject<Item> DEPTHSTONE_BRICKS_STAIRS = block(CatastropheModModBlocks.DEPTHSTONE_BRICKS_STAIRS);
	public static final RegistryObject<Item> TWIG = REGISTRY.register("twig", () -> new TwigItem());
	public static final RegistryObject<Item> SEA_CRYSTAL_GEODE = REGISTRY.register("sea_crystal_geode", () -> new SeaCrystalGeodeItem());
	public static final RegistryObject<Item> HUNTSMAN_KNIFE = REGISTRY.register("huntsman_knife", () -> new HuntsmanKnifeItem());
	public static final RegistryObject<Item> ATLANTIC_SEA_NETTLE_ITEM = REGISTRY.register("atlantic_sea_nettle_item", () -> new AtlanticSeaNettleItemItem());
	public static final RegistryObject<Item> HAUNTED_MIRROR = REGISTRY.register("haunted_mirror", () -> new HauntedMirrorItem());
	public static final RegistryObject<Item> WOODEN_BOW = REGISTRY.register("wooden_bow", () -> new WoodenBowItem());
	public static final RegistryObject<Item> STARLIT_LACEWING_STAFF = REGISTRY.register("starlit_lacewing_staff", () -> new StarlitLacewingStaffItem());
	public static final RegistryObject<Item> SPINACH_LEAVES = REGISTRY.register("spinach_leaves", () -> new SpinachLeavesItem());
	public static final RegistryObject<Item> SPINACH_SOUP = REGISTRY.register("spinach_soup", () -> new SpinachSoupItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(NATURITE_SHIELD.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
		});
	}
}
